[sepolia]
consensus_rpc = "http://unstable.sepolia.beacon-api.nimbus.team"
# execution_rpc = "https://0xrpc.io/sep"
# execution_rpc = "https://1rpc.io/sepolia"
# execution_rpc = "https://eth-sepolia.g.alchemy.com/public"
# execution_rpc = "https://ethereum-sepolia.publicnode.com"
# execution_rpc = "https://eth-sepolia.public.blastapi.io"
# execution_rpc = "https://sepolia.drpc.org"
# execution_rpc = "https://sepolia.rpc.hypersync.xyz/"
# execution_rpc = "https://testnet-rpc.etherspot.io/v1/11155111"
# execution_rpc = "https://go.getblock.io/b5e4e946782a4c079a146e052f550485"
# execution_rpc = "https://eth-sepolia-testnet.rpc.grove.city/v1/01fdb492"
# execution_rpc = "https://api.noderpc.xyz/rpc-sepolia/public"
# execution_rpc = "https://ethereum-sepolia-public.nodies.app"
# execution_rpc = "https://endpoints.omniatech.io/v1/eth/sepolia/public"
execution_rpc = "https://eth-sepolia.api.onfinality.io/public"
# execution_rpc = "https://eth-sepolia.reddio.com/"
# execution_rpc = "https://rpc-sepolia.rockx.com/"
# execution_rpc = "https://ethereum-sepolia.rpc.subquery.network/public"
# execution_rpc = "https://sepolia.gateway.tenderly.co"
# execution_rpc = "https://ethereum-sepolia.therpc.io"
# execution_rpc = "https://sepolia.rpc.thirdweb.com/"
rpc_port = 8545
rpc_bind_ip = "127.0.0.1"
max_checkpoint_age = 86400
load_external_fallback = true

[mainnet]
consensus_rpc = "http://testing.mainnet.beacon-api.nimbus.team/"
# execution_rpc = "https://go.getblock.us/27eb23f40b964c9bb71b62f721e594e7"
execution_rpc = "https://0xrpc.io/eth"
# execution_rpc = "https://1rpc.io/eth"
# execution_rpc = "https://eth-mainnet.g.alchemy.com/public"
# execution_rpc = "https://ethereum.publicnode.com"
# execution_rpc = "https://eth-mainnet.public.blastapi.io"
# execution_rpc = "https://ethereum.blinklabs.xyz/"
# execution_rpc = "https://api.blockeden.xyz/eth/67nCBdZQSH9z3YqDDjdm"
# execution_rpc = "https://ethereum.blockpi.network/v1/rpc/public"
# execution_rpc = "https://eth-protect.rpc.blxrbdn.com"
# execution_rpc = "https://cloudflare-eth.com/v1/mainnet"
# execution_rpc = "https://eth.drpc.org/"
# execution_rpc = "https://api.edennetwork.io/v1/rocket"
# execution_rpc = "https://eth.rpc.hypersync.xyz/"
# execution_rpc = "https://rpc.flashbots.net/"
# execution_rpc = "https://eth.rpc.grove.city/v1/01fdb492"
# execution_rpc = "https://eth.meowrpc.com"
# execution_rpc = "https://eth.leorpc.com/?api_key=FREE"
# execution_rpc = "https://eth.llamarpc.com"
# execution_rpc = "https://eth.merkle.io/"
# execution_rpc = "https://rpc.mevblocker.io"
# execution_rpc = "https://api.noderpc.xyz/rpc-mainnet/public"
# execution_rpc = "https://ethereum-public.nodies.app"
# execution_rpc = "https://public-eth.nownodes.io/"
# execution_rpc = "https://endpoints.omniatech.io/v1/eth/mainnet/public"
# execution_rpc = "https://eth.api.onfinality.io/public"
# execution_rpc = "https://eth-pokt.nodies.app/"
# execution_rpc = "https://ethereum-rpc.polkachu.com/"
# execution_rpc = "https://eth-mainnet.reddio.com/"
# execution_rpc = "https://ethereum.rpc.subquery.network/public"
# execution_rpc = "https://mainnet.gateway.tenderly.co"
# execution_rpc = "https://ethereum.therpc.io"
# execution_rpc = "https://ethereum.rpc.thirdweb.com/"
rpc_port = 8545
rpc_bind_ip = "127.0.0.1"
max_checkpoint_age = 86400
load_external_fallback = true
