set runtimepath^=~/.config/vim
set packpath^=~/.config/vim

" Basic settings
source ~/.config/vim/basic.vim

" Configure languages
source ~/.config/vim/lang/init.vim

" Configure LSP
if !exists("$VIM_NO_LSP")
    source ~/.config/vim/lsp.vim
endif

" Configure plugins
source ~/.config/vim/fern.vim
source ~/.config/vim/howmuch.vim
source ~/.config/vim/snippets.vim

" LLM plugins
source ~/.config/vim/ai.vim
source ~/.config/vim/llama.vim

" fzf
source ~/.config/vim/fzf.vim

" Configure colors
source ~/.config/vim/colors.vim
